---
deploy_registry : true
deploy_web      : true
use_tokens      : true
build_containers: true
install_docker  : true
vagrant         : true

registry_proto  : http
registry_url    : "127.0.0.1:5000"

is_online       : "yes"
tasks_to_build  : "all"

rabbitmq_pass   : "password"
rabbitmq_user   : "user"
pika_addr       : "127.0.0.1"

levels          :
  ## Chain 1 (Beginner)
  # read file
  - name    : suzen1
    password: suzen1
    sault   : "tCY.XnoD"
    flag    : "ZGFpejZhaFJhZVNhZXhhaWJ1YWYK"
    config  : "ls|cd|cat|file|du|find|sh"
    chain   : 1
    # read file
  - name    : suzen2
    password: "ZGFpejZhaFJhZVNhZXhhaWJ1YWYK"
    sault   : "3c9OnFo/"
    flag    : "dGhlaWxpM2FoWm9odGFpM2VldzMK"
    config  : "ls|cd|sh|cat|less|more|head|tail"
    chain   : 1
    # read file
  - name    : suzen3
    password: "dGhlaWxpM2FoWm9odGFpM2VldzMK"
    sault   : "oh3Rh950"
    flag    : "Y284ZWlxdXVlMmllTDNpZXBoNWUK"
    config  : "sh|ls"
    rohome  : "true"
    chain   : 1
    # read file
  - name    : suzen4
    password: "Y284ZWlxdXVlMmllTDNpZXBoNWUK"
    sault   : "rKQAVmA9"
    flag    : "C2HLBODHAER1ZMLLBNV1AGFPOW4K"
    config  : "sh|ls|awk|sed|sort|uniq|cat|find|grep|fold|rm|mv|split|cut|tr|less"
    rohome  : "false"
    chain   : 1

    ## Chain 2 (Talk to nginx)
    # /dev/tcp to nginx
  - name    : suzen5
    password: "suzen5"
    sault   : "Yy9aP4bg"
    config  : "ls|cd|ls|mknod|sh"
    rohome  : "false"
    chain   : 2
    flag: "dmVlNFdvaE42ZWVoMFpvN3dhcGgK"
    servers :
      - name: suzen5server
        flag: "dmVlNFdvaE42ZWVoMFpvN3dhcGgK"

    ## Chain 3 (One line solve)
    # pcap
  - name    : suzen6
    password: "suzen6"
    sault   : "wC41kJyn"
    flag    : "YmllMWVraUQ0YWlxdWU5a2VpcGgK"
    chain   : 3
    # magic
  - name    : suzen7
    password: "YmllMWVraUQ0YWlxdWU5a2VpcGgK"
    sault   : "XJ.z5hxy"
    flag    : "b2hmZWFiZW9HYWl2YWVidThnYWUK"
    chain   : 3
    # process name
  - name    : suzen8
    password: "b2hmZWFiZW9HYWl2YWVidThnYWUK"
    sault   : "PoZ3KIT4"
    flag    : "dmFlSmFpcGhvaGI4Y29oZ2gxeWEK"
    chain   : 3

    ## Chain 4 (maze)
    # maze
  - name    : suzen9
    password: "suzen9"
    sault   :  "UP6ILIjj"
    chain   : 4
    flag: "aWVyNWVvOGluM21haDBRdWFobTkK"
    servers :
      - name: suzen9server
        flag: "aWVyNWVvOGluM21haDBRdWFobTkK"

    ## Chain 5
    # TODO
  - name    : suzen10
    password: "aWVyNWVvOGluM21haDBRdWFobTkK"
    sault   : "uiQs3XQL"
    chain   : 5
    # Recursive folders
  - name    : suzen11
    password: "suzen11"
    sault   : "tCY.XnoD"
    flag    : "aXY3ZWlqZWl5ZWlQaG9vczlhSmEK"
    config  : "ls|cd|cat|file|du|find|sh"
    chain   : 5
    # TODO
  - name    : suzen12
    password: "aXY3ZWlqZWl5ZWlQaG9vczlhSmEK"
    sault   : "tHnyJhTd"
    flag    : "eWFlMEhpZTByYWVwYXRoZWUwYWEK"
    config  : "ls|sh|cd"
    chain   : 5
    # vim
  - name    : suzen13
    password: "suzen13"
    sault   : "tHnyJhTd"
    flag    : "Sm9vbmVlOGVlYzRFaXNob294ZWsK"
    chain   : 5

    ## Chain 6 (basic bash commands)
    # cd
  - name    : suzen14
    password: "suzen14"
    sault   : "DnnfL1Td"
    flag    : "d2FodmFoMWFlV2FpYmVlaG9vMmIK"
    chain   : 6
    # pwd
  - name    : suzen15
    password: "d2FodmFoMWFlV2FpYmVlaG9vMmIK"
    sault   : "DKrmO1xd"
    flag    : "TWVlMXdvaDJ6YWVoZWoyamllNm8K"
    chain   : 6
    # id
  - name    : suzen16
    password: "TWVlMXdvaDJ6YWVoZWoyamllNm8K"
    sault   : "DKr8Jh13"
    flag    : "ZXVsb29naG91MFBob2g4T2hkYWkK"
    chain   : 6
    # ls
  - name    : suzen17
    password: "ZXVsb29naG91MFBob2g4T2hkYWkK"
    sault   : "dcdcUI13"
    flag    : "bmVlNm1lMEhhaU11M2thaGVpNmEK"
    chain   : 6
    # man
  - name    : suzen18
    password: "bmVlNm1lMEhhaU11M2thaGVpNmEK"
    sault   : "KKr8POR3"
    flag    : "Y2hpZWNoM2VpRzRJZWtlaXNlbGUK"
    chain   : 6

    ## Chain 7 (basic bash commands2)
    # mkdir
  - name    : suzen19
    password: "suzen19"
    sault   : "DkOlP1Td"
    flag    : "V2VpMGNvaHNoZWlxdWE0YWhnaG8K"
    chain   : 7
    # rm
  - name    : suzen20
    password: "V2VpMGNvaHNoZWlxdWE0YWhnaG8K"
    sault   : "D2fwe44d"
    flag    : "YW1pZWhpaW0yb2h5NW9vRjZlaXcK"
    chain   : 7
    # rm with filters
  - name    : suzen21
    password: "YW1pZWhpaW0yb2h5NW9vRjZlaXcK"
    sault   : "DggOP112d"
    flag    : "aWU0b29XdWxlaXBodXBpZWZveW8K"
    chain   : 7
    # touch
  - name    : suzen22
    password: "aWU0b29XdWxlaXBodXBpZWZveW8K"
    sault   : "2hvOWpvb"
    flag    : "dXI2dXNhaDNvaFQxaWV2MGNobzgK"
    chain   : 7
    # mv
  - name    : suzen23
    password: "dXI2dXNhaDNvaFQxaWV2MGNobzgK"
    sault   : "cXV1bmcK"
    flag    : "dmVlc2VpQzVBb2dlaXI1cmVlM2YK"
    chain   : 7
    # cp
  - name    : suzen24
    password: "dmVlc2VpQzVBb2dlaXI1cmVlM2YK"
    sault   : "1YXRvaHp"
    flag    : "YWVnaG9venVvejd2b292OHNvaEwK"
    chain   : 7

    ## Chain 8 (basic bash commands3)
    # cat
  - name    : suzen25
    password: "suzen25"
    sault   : "aWJ1YzIK"
    flag    : "dGhlZThhcXVpZUNpTGFpdGhlZTkK"
    chain   : 8
    # less
  - name    : suzen26
    password: "dGhlZThhcXVpZUNpTGFpdGhlZTkK"
    sault   : "ZWNvaHhl"
    flag    : "WWVpc2gxYWlndXVrZWl5ZWloaWUK"
    config  : "less|ls|sh"
    chain   : 8
    # tail
  - name    : suzen27
    password: "WWVpc2gxYWlndXVrZWl5ZWloaWUK"
    sault   : "GE0ZWlQ"
    flag    : "dGVlMUtleThhUXVvaDFnZTFiaWkK"
    chain   : 8
    # cat eof + echo
  - name    : suzen28
    password: "dGVlMUtleThhUXVvaDFnZTFiaWkK"
    sault   : "V5YWVUaW"
    flag    : "ZWV4b1g1WnVkMm9oZnVjYWhkdTMK"
    config  : "sh|ls|cd|cat|md5sum|mkdir"
    chain   : 8
    # echo -e
  - name    : suzen29
    password: "ZWV4b1g1WnVkMm9oZnVjYWhkdTMK"
    sault   : "Glldm9vO"
    flag    : "dmFvbmcwcGFlMWlodUJvaFppZWQK"
    config  : "sh"
    chain   : 8

    ## Chain 9
    # base64 + curl
  - name    : suzen901
    password: "suzen901"
    sault   : "HuvDAeWs"
    chain   : 9
    flag: "hFYhnDBGmSsfDltJnkkNgYGUnwdK"
    servers :
      - name: suzen901server
        flag: "hFYhnDBGmSsfDltJnkkNgYGUnwdK"

    ## Chain 11 (grep challenge)
    # grep -c
  - name    : suzen1101
    password: "suzen1101"
    sault   : "eiGohC9k"
    flag    : "aid5looch4Auth1vig5eye8Zoh0t"
    chain   : 11
    # grep -r
  - name    : suzen1102
    password: "aid5looch4Auth1vig5eye8Zoh0t"
    sault   : "Zijuo2Mo"
    flag    : "Q2hhaHdldm9vd2llM0FhaG9vM2EK"
    chain   : 11
    # grep
  - name    : suzen1103
    password: "Q2hhaHdldm9vd2llM0FhaG9vM2EK"
    sault   : "hue8ahQu"
    flag    : "RWZhZTBhaVc2eXVhcGg3ZGVlcnUK"
    chain   : 11
    # grep -L
  - name    : suzen1104
    password: "RWZhZTBhaVc2eXVhcGg3ZGVlcnUK"
    sault   : "DaoW7gai"
    flag    : "cG9vd29oNHViMVZpdzBCZWFqb28K"
    chain   : 11

    ## Chain 16
    # find
  - name    : suzen1601
    password: "suzen1601"
    sault   : "Rc6uI4vD"
    flag    : "cjs60vS8vl3nfieCuvNal0fV74en"
    chain   : 16
    # find
  - name    : suzen1602
    password: "cjs60vS8vl3nfieCuvNal0fV74en"
    sault   : "eiGohC9k"
    flag    : "SWVwb292NU9obmdpNm9vamFoQ2gK"
    chain   : 16
    # find
  - name    : suzen1603
    password: "SWVwb292NU9obmdpNm9vamFoQ2gK"
    sault   : "Zijuo2Mo"
    flag    : "MKzgASrjByzdIaTdpaTdq2vzAIgY"
    chain   : 16
    # find
  - name    : suzen1604
    password: "MKzgASrjByzdIaTdpaTdq2vzAIgY"
    sault   : "Zijuo2Mo"
    flag    : "K82T5UWZjlWYzUnal9mS2g2cpFGb"
    chain   : 16

    ## Chain 14 (sort)
    # sort -u
  - name    : suzen1401
    password: suzen1401
    sault   : "vsKnvJak"
    flag    : "GHsdgidAOJFEIJfdsknvajkfajbK"
    chain   : 14

    ## Chain 15 
    # tar
  - name    : suzen1501
    password: "suzen1501"
    sault   : "vsiuyTqw"
    flag    : "4bf47e277be11d43b6817748359b"
    chain   : 15
    # 
  - name    : suzen1502
    password: "4bf47e277be11d43b6817748359b"
    sault   : "3dsai45d"
    flag    : "217e09Qff7cd34c44f37cd17f347"
    chain   : 15


## EXAMPLE TEMPLATE
#  - name    : suzen
#    password: ""
#    sault   : ""
#    flag    : ""
#    config  : ""
#    chain   : ""
