- name: install python pkgs
  apt :
    name: ['python3-pip', 'python3-setuptools', 'python-setuptools']

- set_fact:
    requirements: "{{ lookup('file', './requirements.txt').splitlines() }}"
- debug: var=requirements

- name: install requirements for builder
  pip :
    executable: pip3
    name      : "{{ requirements }}"

- name    : build tasks
  shell   : "cd /vagrant && ./build.py {{ tasks_to_build | default('all') }}"
  retries : 3
  delay   : 3
  register: result
  until   : result is not failed
  when    : vagrant|bool == true

- name      : build tasks
  shell     : "cd ../; ./build.py {{ tasks_to_build | default('all') }}"
  retries   : 3
  delay     : 3
  register  : result
  until     : result is not failed
  when      : vagrant|bool == false
  connection: local
  tags      : test
  become    : no
